import { fileName, topFolder, withoutMarkdownExtension } from "../../core/files.js";
import { serializeNote } from "../../markdown/frontmatter.js";
import { frontmatterString, type Note } from "../../vault/note.js";
import type { Vault } from "../../vault/vault.js";

export const CATALOG_SUMMARY = "Catalog of every note with its one-line summary";
const ROOT_GROUP = "Root";

function linkName(vault: Vault, note: Note): string {
  const stem = withoutMarkdownExtension(note.path);
  const base = fileName(stem);
  const resolution = vault.resolve(base);
  return resolution.status === "found" && resolution.path === note.path ? base : stem;
}

function catalogLine(vault: Vault, note: Note): string {
  const name = linkName(vault, note);
  const link = name === note.title ? `[[${name}]]` : `[[${name}|${note.title}]]`;
  const type = frontmatterString(note, "type");
  const details = [type === null ? null : `\`${type}\``, frontmatterString(note, "summary")].filter(
    (part) => part !== null,
  );
  return details.length === 0 ? `- ${link}` : `- ${link} · ${details.join(" ")}`;
}

function groupByFolder(notes: readonly Note[]): [string, Note[]][] {
  const groups = new Map<string, Note[]>();
  for (const note of notes) {
    const folder = topFolder(note.path);
    groups.set(folder, [...(groups.get(folder) ?? []), note]);
  }
  return [...groups].sort(([a], [b]) => (a === "" ? -1 : b === "" ? 1 : a.localeCompare(b)));
}

export function renderCatalog(vault: Vault): { text: string; count: number } {
  const notes = vault.notes().filter((note) => note.path !== vault.config.index.path);
  const sections = groupByFolder(notes).map(([folder, items]) =>
    [`## ${folder || ROOT_GROUP}`, "", ...items.map((note) => catalogLine(vault, note))].join("\n"),
  );
  const body = [
    "# Index",
    "",
    `Catalog of the vault, generated by brain-mcp from each note's summary. ${String(notes.length)} notes.`,
    "",
    sections.join("\n\n"),
  ].join("\n");
  return {
    text: serializeNote({ type: "index", summary: CATALOG_SUMMARY }, body),
    count: notes.length,
  };
}
